//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranjaSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A460EB_PruebasNGS2Entities : DbContext
    {
        public DB_A460EB_PruebasNGS2Entities()
            : base("name=DB_A460EB_PruebasNGS2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCerdas> Cerdas { get; set; }
        public virtual DbSet<tblControlLechones> ControlLechones { get; set; }
        public virtual DbSet<tblDetalleLotes> DetalleLotes { get; set; }
        public virtual DbSet<tblEmpleados> Empleados { get; set; }
        public virtual DbSet<tblFichas> Fichas { get; set; }
        public virtual DbSet<tblGeneticas> Geneticas { get; set; }
        public virtual DbSet<tblLechones> Lechones { get; set; }
        public virtual DbSet<tblLotes> Lotes { get; set; }
        public virtual DbSet<tblRoles> Roles { get; set; }
        public virtual DbSet<tblUsuarios> Usuarios { get; set; }
        public virtual DbSet<tblVacunas> Vacunas { get; set; }
        public virtual DbSet<tblVacunasLotes> VacunasLotes { get; set; }
        public virtual DbSet<tblVarracos> Varracos { get; set; }
    }
}
