//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranjaSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDGranja : DbContext
    {
        public BDGranja()
            : base("name=BDGranja")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCerdas> tblCerdas { get; set; }
        public virtual DbSet<tblControlLechones> tblControlLechones { get; set; }
        public virtual DbSet<tblDetalleLotes> tblDetalleLotes { get; set; }
        public virtual DbSet<tblEmpleados> tblEmpleados { get; set; }
        public virtual DbSet<tblFichas> tblFichas { get; set; }
        public virtual DbSet<tblGeneticas> tblGeneticas { get; set; }
        public virtual DbSet<tblLechones> tblLechones { get; set; }
        public virtual DbSet<tblLotes> tblLotes { get; set; }
        public virtual DbSet<tblRoles> tblRoles { get; set; }
        public virtual DbSet<tblUsuarios> tblUsuarios { get; set; }
        public virtual DbSet<tblVacunas> tblVacunas { get; set; }
        public virtual DbSet<tblVacunasLotes> tblVacunasLotes { get; set; }
        public virtual DbSet<tblVarracos> tblVarracos { get; set; }
    }
}
