//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranjaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCerdas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCerdas()
        {
            this.tblControlLechones = new HashSet<tblControlLechones>();
            this.tblDetalleLotes = new HashSet<tblDetalleLotes>();
            this.tblFichas = new HashSet<tblFichas>();
            this.tblVacunas = new HashSet<tblVacunas>();
        }
    
        public int IdCerda { get; set; }
        public int NumCerda { get; set; }
        public string Procedencia { get; set; }
        public string Observaciones { get; set; }
        public int NumParto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Estado { get; set; }
        public int IdGenetica { get; set; }
    
        public virtual tblGeneticas tblGeneticas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblControlLechones> tblControlLechones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetalleLotes> tblDetalleLotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFichas> tblFichas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVacunas> tblVacunas { get; set; }
    }
}
