//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranjaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblControlLechones
    {
        public int IdControlL { get; set; }
        public int IdLotes { get; set; }
        public string FechaDestete { get; set; }
        public int IdCerda { get; set; }
        public int TotalLechones { get; set; }
        public double PesoPromedioL { get; set; }
        public Nullable<int> Lotes_IdLote { get; set; }
    
        public virtual tblCerdas tblCerdas { get; set; }
        public virtual tblLotes tblLotes { get; set; }
    }
}
