//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranjaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFichas
    {
        public int IdFicha { get; set; }
        public int IdCerda { get; set; }
        public int NumParto { get; set; }
        public string FechaServio { get; set; }
        public int IdVarraco { get; set; }
        public string FechaParto { get; set; }
        public Nullable<int> NacidosVivos { get; set; }
        public Nullable<int> NacidosMuertos { get; set; }
        public Nullable<int> NacidosMomias { get; set; }
        public Nullable<int> TotalNacidos { get; set; }
        public Nullable<decimal> PesoPromedio1D { get; set; }
        public Nullable<int> NumDestetado { get; set; }
        public Nullable<decimal> PesoPromedio28D { get; set; }
        public string FechaDestete { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<int> Lote { get; set; }
    
        public virtual tblCerdas tblCerdas { get; set; }
        public virtual tblEmpleados tblEmpleados { get; set; }
        public virtual tblVarracos tblVarracos { get; set; }
    }
}
