//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranjaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLechones
    {
        public int IdLechones { get; set; }
        public int NumLote { get; set; }
        public int Edad { get; set; }
        public int NCerdos { get; set; }
        public int NCerdas { get; set; }
        public int NVarracos { get; set; }
        public string Fases { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Estado { get; set; }
        public decimal qqDiarios { get; set; }
        public decimal qqSemanal { get; set; }
    }
}
